version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Hsn723"
    allow:
      - dependency-type: "all"
    groups:
      k8s:
        patterns:
          - "k8s.io/*"
          - "^sigs.k8s.io/*"
      ginkgo:
        patterns:
          - "^github.com/onsi/*"
      other:
        patterns:
          - "*"
        exclude-patterns:
          - "^k8s.io/*"
          - "^sigs.k8s.io/*"
          - "^github.com/onsi/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "Hsn723"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "Hsn723"
