linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - forbidigo
    - gocognit
    - goconst
    - gocyclo
    - godot
    - gosimple
    - gofmt
    - ineffassign
    - revive
    - staticcheck
    - unparam
    - unused
run:
  timeout: 5m
