# permissions for end users to edit dkimkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dkimkey-editor-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - dkim-manager.atelierhsn.com
  resources:
  - dkimkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dkim-manager.atelierhsn.com
  resources:
  - dkimkeys/status
  verbs:
  - get
