apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ template "dkim-manager.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dkim-manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
