name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/dkim-manager/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@089cefcb7878b60fd367cf193696d04a7e6dbec3 # v1.0.17
    secrets: inherit
    with:
      extra_helm_setup: |
        helm repo add external-dns https://kubernetes-sigs.github.io/external-dns
        helm repo update
      upload_as_oci: true
      chart_name: dkim-manager
