name: Release Helm chart
on:
  push:
    branches:
      - master
    paths:
      - 'charts/dkim-manager/Chart.yaml'
permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/helm-release.yml@b795c900fe8637e50b2ed1c91a5a8b211ba52dd8 # v1.0.32
    secrets: inherit
    with:
      extra_helm_setup: |
        helm repo add external-dns https://kubernetes-sigs.github.io/external-dns
        helm repo update
      upload_as_oci: true
      chart_name: dkim-manager
