name: release
on:
  push:
    branches:
      - master
    paths:
      - VERSION
permissions:
  contents: write
  id-token: write
  packages: write
  attestations: write
jobs:
  release:
    uses: hsn723/actions/.github/workflows/release.yml@089cefcb7878b60fd367cf193696d04a7e6dbec3 # v1.0.17
    secrets: inherit
